--------------------------------------------------------
--  File created - Sexta-feira-Dezembro-06-2013   
--------------------------------------------------------
DROP TABLE "PSI001PL"."ADDRESS" cascade constraints;
DROP TABLE "PSI001PL"."ADDRESSTYPE" cascade constraints;
DROP TABLE "PSI001PL"."CATEGORY" cascade constraints;
DROP TABLE "PSI001PL"."COUNTRY" cascade constraints;
DROP TABLE "PSI001PL"."CUSTOMER" cascade constraints;
DROP TABLE "PSI001PL"."CUSTOMER_ADDRESS" cascade constraints;
DROP TABLE "PSI001PL"."IMAGE" cascade constraints;
DROP TABLE "PSI001PL"."PAYOPTION" cascade constraints;
DROP TABLE "PSI001PL"."PRODUCT" cascade constraints;
DROP TABLE "PSI001PL"."SYSTEMUSER" cascade constraints;
DROP TABLE "PSI001PL"."TRANSACTION" cascade constraints;
DROP TABLE "PSI001PL"."TRANSACTIONLINE" cascade constraints;
DROP TABLE "PSI001PL"."USERTYPE" cascade constraints;
DROP SEQUENCE "PSI001PL"."ADDRESSTYPE_ADDRESSTYPE_ID_SEQ";
DROP SEQUENCE "PSI001PL"."ADDRESS_ADDRESS_ID_SEQ";
DROP SEQUENCE "PSI001PL"."CATEGORY_CATEGORY_ID_SEQ";
DROP SEQUENCE "PSI001PL"."COUNTRY_COUNTRY_ID_SEQ";
DROP SEQUENCE "PSI001PL"."CUSTOMER_CUSTOMER_ID_SEQ";
DROP SEQUENCE "PSI001PL"."IMAGE_IMAGE_ID_SEQ";
DROP SEQUENCE "PSI001PL"."PAYOPTION_PAYOPTION_ID_SEQ";
DROP SEQUENCE "PSI001PL"."PRODUCT_PRODUCT_ID_SEQ";
DROP SEQUENCE "PSI001PL"."SYSTEMUSER_SYSTEMUSER_ID_SEQ";
DROP SEQUENCE "PSI001PL"."TRANSACTIONLINE_TRANSACTIONLIN";
DROP SEQUENCE "PSI001PL"."TRANSACTION_TRANSACTION_ID_SEQ";
DROP SEQUENCE "PSI001PL"."USERTYPE_USERTYPE_ID_SEQ";
--------------------------------------------------------
--  DDL for Sequence ADDRESSTYPE_ADDRESSTYPE_ID_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "PSI001PL"."ADDRESSTYPE_ADDRESSTYPE_ID_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 3 NOCACHE  ORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence ADDRESS_ADDRESS_ID_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "PSI001PL"."ADDRESS_ADDRESS_ID_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 6 NOCACHE  ORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence CATEGORY_CATEGORY_ID_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "PSI001PL"."CATEGORY_CATEGORY_ID_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 4 NOCACHE  ORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence COUNTRY_COUNTRY_ID_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "PSI001PL"."COUNTRY_COUNTRY_ID_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 3 NOCACHE  ORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence CUSTOMER_CUSTOMER_ID_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "PSI001PL"."CUSTOMER_CUSTOMER_ID_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 6 NOCACHE  ORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence IMAGE_IMAGE_ID_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "PSI001PL"."IMAGE_IMAGE_ID_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 16 NOCACHE  ORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence PAYOPTION_PAYOPTION_ID_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "PSI001PL"."PAYOPTION_PAYOPTION_ID_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 5 NOCACHE  ORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence PRODUCT_PRODUCT_ID_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "PSI001PL"."PRODUCT_PRODUCT_ID_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 16 NOCACHE  ORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SYSTEMUSER_SYSTEMUSER_ID_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "PSI001PL"."SYSTEMUSER_SYSTEMUSER_ID_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 3 NOCACHE  ORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence TRANSACTIONLINE_TRANSACTIONLIN
--------------------------------------------------------

   CREATE SEQUENCE  "PSI001PL"."TRANSACTIONLINE_TRANSACTIONLIN"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 7 NOCACHE  ORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence TRANSACTION_TRANSACTION_ID_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "PSI001PL"."TRANSACTION_TRANSACTION_ID_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 4 NOCACHE  ORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence USERTYPE_USERTYPE_ID_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "PSI001PL"."USERTYPE_USERTYPE_ID_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  ORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Table ADDRESS
--------------------------------------------------------

  CREATE TABLE "PSI001PL"."ADDRESS" 
   (	"ADDRESS_ID" NUMBER, 
	"STREET" VARCHAR2(255 BYTE), 
	"CITY" VARCHAR2(60 BYTE), 
	"POSTALCODE" VARCHAR2(12 BYTE), 
	"COUNTRY_COUNTRY_ID" NUMBER, 
	"ADDRESSTYPE_ADDRESSTYPE_ID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PSI" ;
--------------------------------------------------------
--  DDL for Table ADDRESSTYPE
--------------------------------------------------------

  CREATE TABLE "PSI001PL"."ADDRESSTYPE" 
   (	"ADDRESSTYPE_ID" NUMBER, 
	"NAME" VARCHAR2(60 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PSI" ;
--------------------------------------------------------
--  DDL for Table CATEGORY
--------------------------------------------------------

  CREATE TABLE "PSI001PL"."CATEGORY" 
   (	"CATEGORY_ID" NUMBER, 
	"NAME" VARCHAR2(60 BYTE), 
	"IMAGESOURCE" VARCHAR2(2048 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PSI" ;
--------------------------------------------------------
--  DDL for Table COUNTRY
--------------------------------------------------------

  CREATE TABLE "PSI001PL"."COUNTRY" 
   (	"COUNTRY_ID" NUMBER, 
	"NAME" VARCHAR2(120 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PSI" ;
--------------------------------------------------------
--  DDL for Table CUSTOMER
--------------------------------------------------------

  CREATE TABLE "PSI001PL"."CUSTOMER" 
   (	"CUSTOMER_ID" NUMBER, 
	"EMAIL" VARCHAR2(255 BYTE), 
	"USERNAME" VARCHAR2(60 BYTE), 
	"PASSWORD" CHAR(40 BYTE), 
	"NAME" VARCHAR2(160 BYTE), 
	"NIF" NUMBER(*,0), 
	"PHONENR" VARCHAR2(16 BYTE), 
	"PAYPAL" VARCHAR2(255 BYTE),
	"ALERTSMS" NUMBER DEFAULT 0, 
	"ALERTEMAIL" NUMBER DEFAULT 0, 
	"ALERTNUMDAYS" NUMBER DEFAULT 1
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PSI" ;
--------------------------------------------------------
--  DDL for Table CUSTOMER_ADDRESS
--------------------------------------------------------

  CREATE TABLE "PSI001PL"."CUSTOMER_ADDRESS" 
   (	"CUSTOMER_CUSTOMER_ID" NUMBER, 
	"ADDRESS_ADDRESS_ID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PSI" ;
--------------------------------------------------------
--  DDL for Table IMAGE
--------------------------------------------------------

  CREATE TABLE "PSI001PL"."IMAGE" 
   (	"IMAGE_ID" NUMBER, 
	"SOURCE" VARCHAR2(2048 BYTE), 
	"PRODUCT_PRODUCT_ID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PSI" ;
--------------------------------------------------------
--  DDL for Table PAYOPTION
--------------------------------------------------------

  CREATE TABLE "PSI001PL"."PAYOPTION" 
   (	"PAYOPTION_ID" NUMBER(*,0), 
	"NAME" VARCHAR2(60 BYTE), 
	"CARDNR" CHAR(16 BYTE), 
	"EXPIRYDATE" CHAR(5 BYTE), 
	"SECURITYCODE" CHAR(3 BYTE), 
	"CUSTOMER_CUSTOMER_ID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PSI" ;
--------------------------------------------------------
--  DDL for Table PRODUCT
--------------------------------------------------------

  CREATE TABLE "PSI001PL"."PRODUCT" 
   (	"PRODUCT_ID" NUMBER, 
	"NAME" VARCHAR2(80 BYTE), 
	"DESCRIPTION" VARCHAR2(255 BYTE), 
	"CODE" VARCHAR2(40 BYTE), 
	"BUYPRICE" FLOAT(126), 
	"SELLPRICE" FLOAT(126), 
	"SHOWDATE" DATE, 
	"STARTTIME" CHAR(5 BYTE), 
	"ENDTIME" CHAR(5 BYTE), 
	"CATEGORY_CATEGORY_ID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PSI" ;
--------------------------------------------------------
--  DDL for Table SYSTEMUSER
--------------------------------------------------------

  CREATE TABLE "PSI001PL"."SYSTEMUSER" 
   (	"SYSTEMUSER_ID" NUMBER, 
	"NAME" VARCHAR2(120 BYTE), 
	"USERNAME" VARCHAR2(30 BYTE), 
	"PASSWORD" CHAR(40 BYTE), 
	"EMAIL" VARCHAR2(255 BYTE), 
	"USERTYPE_USERTYPE_ID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PSI" ;
--------------------------------------------------------
--  DDL for Table TRANSACTION
--------------------------------------------------------

  CREATE TABLE "PSI001PL"."TRANSACTION" 
   (	"TRANSACTION_ID" NUMBER, 
	"PURCHASEDATE" DATE, 
	"CUSTOMER_CUSTOMER_ID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PSI" ;
--------------------------------------------------------
--  DDL for Table TRANSACTIONLINE
--------------------------------------------------------

  CREATE TABLE "PSI001PL"."TRANSACTIONLINE" 
   (	"TRANSACTIONLINE_ID" NUMBER, 
	"QUANTITY" NUMBER(*,0), 
	"PRICEPERUNIT" FLOAT(126), 
	"TRANSACTION_TRANSACTION_ID" NUMBER, 
	"PRODUCT_PRODUCT_ID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PSI" ;
--------------------------------------------------------
--  DDL for Table USERTYPE
--------------------------------------------------------

  CREATE TABLE "PSI001PL"."USERTYPE" 
   (	"USERTYPE_ID" NUMBER, 
	"NAME" VARCHAR2(40 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PSI" ;
REM INSERTING into PSI001PL.ADDRESS
SET DEFINE OFF;
Insert into PSI001PL.ADDRESS (ADDRESS_ID,STREET,CITY,POSTALCODE,COUNTRY_COUNTRY_ID,ADDRESSTYPE_ADDRESSTYPE_ID) values (1,'Rua do Norte 35 3E','Lisboa','1000-100',1,1);
Insert into PSI001PL.ADDRESS (ADDRESS_ID,STREET,CITY,POSTALCODE,COUNTRY_COUNTRY_ID,ADDRESSTYPE_ADDRESSTYPE_ID) values (2,'Avenida da Boavista 16 1D','Porto','4000-100',1,1);
Insert into PSI001PL.ADDRESS (ADDRESS_ID,STREET,CITY,POSTALCODE,COUNTRY_COUNTRY_ID,ADDRESSTYPE_ADDRESSTYPE_ID) values (3,'Rua Lu�s de Cam�es 2 2D','Coimbra','3000-100',1,1);
Insert into PSI001PL.ADDRESS (ADDRESS_ID,STREET,CITY,POSTALCODE,COUNTRY_COUNTRY_ID,ADDRESSTYPE_ADDRESSTYPE_ID) values (4,'Rua Bela de S�o Tiago 47','Funchal','9000-100',1,1);
Insert into PSI001PL.ADDRESS (ADDRESS_ID,STREET,CITY,POSTALCODE,COUNTRY_COUNTRY_ID,ADDRESSTYPE_ADDRESSTYPE_ID) values (5,'Rua da Junqueira 247','Lisboa','1600-100',1,1);
REM INSERTING into PSI001PL.ADDRESSTYPE
SET DEFINE OFF;
Insert into PSI001PL.ADDRESSTYPE (ADDRESSTYPE_ID,NAME) values (1,'Entrega');
Insert into PSI001PL.ADDRESSTYPE (ADDRESSTYPE_ID,NAME) values (2,'Fatura��o');
REM INSERTING into PSI001PL.CATEGORY
SET DEFINE OFF;
Insert into PSI001PL.CATEGORY (CATEGORY_ID,NAME,IMAGESOURCE) values (1,'Artesanato','http://www.infoescola.com/wp-content/uploads/2009/12/artesanato2.JPG');
Insert into PSI001PL.CATEGORY (CATEGORY_ID,NAME,IMAGESOURCE) values (2,'Confeitaria','http://estrelapadaria.com/ESW/Images/confeitaria.jpg');
Insert into PSI001PL.CATEGORY (CATEGORY_ID,NAME,IMAGESOURCE) values (3,'Espet�culo','http://2.bp.blogspot.com/_gzp2oQw42zs/TCiwGE5z3qI/AAAAAAAABg8/JIygCPCktMU/s1600/O+grupo+Soarte+de+teatro+encerra+o+Festival+de+M%C3%BAsica+com+o+espet%C3%A1culo+Noel,+o+Feiti%C3%A7o+da+Vila.+%C3%89+dia+25+de+julho+no+Teatro..JPG');
REM INSERTING into PSI001PL.COUNTRY
SET DEFINE OFF;
Insert into PSI001PL.COUNTRY (COUNTRY_ID,NAME) values (1,'Portugal');
Insert into PSI001PL.COUNTRY (COUNTRY_ID,NAME) values (2,'Espanha');
REM INSERTING into PSI001PL.CUSTOMER
SET DEFINE OFF;
Insert into PSI001PL.CUSTOMER (CUSTOMER_ID,EMAIL,USERNAME,PASSWORD,NAME,NIF,PHONENR,PAYPAL) values (1,'maria@mail.pt','maria','99efd3054ce4aeb093d7864ac6e0e29ccb6fa4a9','Maria Silva',200000001,'913772301',null);
Insert into PSI001PL.CUSTOMER (CUSTOMER_ID,EMAIL,USERNAME,PASSWORD,NAME,NIF,PHONENR,PAYPAL) values (2,'joao@mail.pt','joao','99efd3054ce4aeb093d7864ac6e0e29ccb6fa4a9','Jo�o Sousa',200000002,'934573747','joao@mail.pt');
Insert into PSI001PL.CUSTOMER (CUSTOMER_ID,EMAIL,USERNAME,PASSWORD,NAME,NIF,PHONENR,PAYPAL) values (3,'manuel@mail.pt','manuel','99efd3054ce4aeb093d7864ac6e0e29ccb6fa4a9','Manuel Ribeiro',200000003,'924752103','manuel@mail.pt');
Insert into PSI001PL.CUSTOMER (CUSTOMER_ID,EMAIL,USERNAME,PASSWORD,NAME,NIF,PHONENR,PAYPAL) values (4,'carla@mail.pt','carla','99efd3054ce4aeb093d7864ac6e0e29ccb6fa4a9','Carla Rodrigues',200000004,'961438901','carla@mail.pt');
Insert into PSI001PL.CUSTOMER (CUSTOMER_ID,EMAIL,USERNAME,PASSWORD,NAME,NIF,PHONENR,PAYPAL) values (5,'cajo@mail.pt','carlinhos','99efd3054ce4aeb093d7864ac6e0e29ccb6fa4a9','Carlos Jorge',200000005,'965443324',null);
REM INSERTING into PSI001PL.CUSTOMER_ADDRESS
SET DEFINE OFF;
Insert into PSI001PL.CUSTOMER_ADDRESS (CUSTOMER_CUSTOMER_ID,ADDRESS_ADDRESS_ID) values (1,1);
Insert into PSI001PL.CUSTOMER_ADDRESS (CUSTOMER_CUSTOMER_ID,ADDRESS_ADDRESS_ID) values (2,2);
Insert into PSI001PL.CUSTOMER_ADDRESS (CUSTOMER_CUSTOMER_ID,ADDRESS_ADDRESS_ID) values (3,3);
Insert into PSI001PL.CUSTOMER_ADDRESS (CUSTOMER_CUSTOMER_ID,ADDRESS_ADDRESS_ID) values (4,4);
Insert into PSI001PL.CUSTOMER_ADDRESS (CUSTOMER_CUSTOMER_ID,ADDRESS_ADDRESS_ID) values (5,5);
REM INSERTING into PSI001PL.IMAGE
SET DEFINE OFF;
Insert into PSI001PL.IMAGE (IMAGE_ID,SOURCE,PRODUCT_PRODUCT_ID) values (1,'http://upload.wikimedia.org/wikipedia/commons/thumb/3/3b/PA2900302_galo_emiliarocha_medio.jpg/220px-PA2900302_galo_emiliarocha_medio.jpg',1);
Insert into PSI001PL.IMAGE (IMAGE_ID,SOURCE,PRODUCT_PRODUCT_ID) values (2,'http://upload.wikimedia.org/wikipedia/commons/e/e3/Zepovinho.jpg',2);
Insert into PSI001PL.IMAGE (IMAGE_ID,SOURCE,PRODUCT_PRODUCT_ID) values (3,'http://upload.wikimedia.org/wikipedia/commons/d/d1/Ovos_moles.jpg',3);
Insert into PSI001PL.IMAGE (IMAGE_ID,SOURCE,PRODUCT_PRODUCT_ID) values (4,'http://upload.wikimedia.org/wikipedia/commons/thumb/1/1b/Past%C3%A9is_de_Bel%C3%A9m.JPG/320px-Past%C3%A9is_de_Bel%C3%A9m.JPG',4);
Insert into PSI001PL.IMAGE (IMAGE_ID,SOURCE,PRODUCT_PRODUCT_ID) values (5,'http://festivalpanda.pt/images/panda_home.png',5);
Insert into PSI001PL.IMAGE (IMAGE_ID,SOURCE,PRODUCT_PRODUCT_ID) values (6,'http://cinema.universiablogs.net/files/festival_gelo1.jpg',6);
Insert into PSI001PL.IMAGE (IMAGE_ID,SOURCE,PRODUCT_PRODUCT_ID) values (7,'http://www.feitoria.com.pt/fotos/produtos/-pb253142_1293964287.jpg',7);
Insert into PSI001PL.IMAGE (IMAGE_ID,SOURCE,PRODUCT_PRODUCT_ID) values (8,'http://www.feitoria.com.pt/fotos/produtos/mg7581_1326651901.jpg',8);
Insert into PSI001PL.IMAGE (IMAGE_ID,SOURCE,PRODUCT_PRODUCT_ID) values (9,'http://www.feitoria.com.pt/fotos/produtos/lenco_tabaqueiro_1194267961.jpg',9);
Insert into PSI001PL.IMAGE (IMAGE_ID,SOURCE,PRODUCT_PRODUCT_ID) values (10,'http://www.docesregionais.com/wp-content/uploads/2013/11/Pinhoada-Alc%C3%A1cer-do-Sal.jpg',10);
Insert into PSI001PL.IMAGE (IMAGE_ID,SOURCE,PRODUCT_PRODUCT_ID) values (11,'http://docesportugueses.com/wp-content/uploads/2012/03/P%C3%A3o-de-l%C3%B3_de_Vizela-Bolinhol.jpg',11);
Insert into PSI001PL.IMAGE (IMAGE_ID,SOURCE,PRODUCT_PRODUCT_ID) values (12,'http://docesportugueses.com/wp-content/uploads/2012/03/Doces-Brancos.jpg',12);
Insert into PSI001PL.IMAGE (IMAGE_ID,SOURCE,PRODUCT_PRODUCT_ID) values (13,'http://thumbs.sapo.pt/?epic=48F2K573Wr3b2rk7PzgQzyEcQqnFMNQffv1k/GpR8luVoPyWj1GwnS1J/Yxnn8bM6mPbA+A7bN6FCIs7r68lSb0rx+G5yn5HyphrfVF6z3HN1azl3kqxOnExh9UxYlxDqSnczMQQo/5AN38dr2+laFZBiw==&Q=46&crop=center&errorpic=transparent&W=340',13);
Insert into PSI001PL.IMAGE (IMAGE_ID,SOURCE,PRODUCT_PRODUCT_ID) values (14,'http://thumbs.sapo.pt/?epic=rmvjVi4/O0t20xhlCE+t1gpiULCS3B+izui98IF1aybtut0OVpqbaJ55e1stE0Q6/P0MQDOxWDGAGM3EvyhBcDk3mARhDSrYPwVC4ll3oBLoMd7U1m69mBg5zQcJYW/i58xMXPIJSXFCPK71SiXpjVRIkQ==&Q=46&crop=center&errorpic=transparent&W=340',14);
Insert into PSI001PL.IMAGE (IMAGE_ID,SOURCE,PRODUCT_PRODUCT_ID) values (15,'http://thumbs.sapo.pt/?epic=rmvjVi4/O0t20xhlCE+t1gpiULCS3B+izui98IF1aybtut0OVpqbaJ55e1stE0Q6/P0MFL1m70KvjG9rU3zORw0gV/iXUAebUu8kEjaHkuVcp9/dIe5kjqhnfdcS5ip7AV8jCw1lkPGxhElBIi3mL3/GCw==&Q=46&crop=center&errorpic=transparent&W=340',15);
REM INSERTING into PSI001PL.PAYOPTION
SET DEFINE OFF;
Insert into PSI001PL.PAYOPTION (PAYOPTION_ID,NAME,CARDNR,EXPIRYDATE,SECURITYCODE,CUSTOMER_CUSTOMER_ID) values (1,'Maria Silva','0038001238012735','2014 ','102',1);
Insert into PSI001PL.PAYOPTION (PAYOPTION_ID,NAME,CARDNR,EXPIRYDATE,SECURITYCODE,CUSTOMER_CUSTOMER_ID) values (2,'Jo�o Sousa','0056722346640012','2014 ','709',2);
Insert into PSI001PL.PAYOPTION (PAYOPTION_ID,NAME,CARDNR,EXPIRYDATE,SECURITYCODE,CUSTOMER_CUSTOMER_ID) values (3,'Manuel Ribeiro','0049034883487347','2015 ','098',3);
Insert into PSI001PL.PAYOPTION (PAYOPTION_ID,NAME,CARDNR,EXPIRYDATE,SECURITYCODE,CUSTOMER_CUSTOMER_ID) values (4,'Carla Rodrigues','0433051224454767','2014 ','654',4);
REM INSERTING into PSI001PL.PRODUCT
SET DEFINE OFF;
Insert into PSI001PL.PRODUCT (PRODUCT_ID,NAME,DESCRIPTION,CODE,BUYPRICE,SELLPRICE,SHOWDATE,STARTTIME,ENDTIME,CATEGORY_CATEGORY_ID) values (1,'Galo de Barcelos','Artesanato minhoto, geralmente de barro, � um s�mbolo de Portugal e foi adotado pelo Gil Vicente como sua mascote.','A000000001',1.5,3.99,null,null,null,1);
Insert into PSI001PL.PRODUCT (PRODUCT_ID,NAME,DESCRIPTION,CODE,BUYPRICE,SELLPRICE,SHOWDATE,STARTTIME,ENDTIME,CATEGORY_CATEGORY_ID) values (2,'Z� Povinho','Figura marcante da caricatura de Bordalo Pinheiro.','A000000002',1.2,3.49,null,null,null,1);
Insert into PSI001PL.PRODUCT (PRODUCT_ID,NAME,DESCRIPTION,CODE,BUYPRICE,SELLPRICE,SHOWDATE,STARTTIME,ENDTIME,CATEGORY_CATEGORY_ID) values (3,'Ovos Moles','Doce regional, tradicional da pastelaria aveirense.','C000000001',5.5,8.2,null,null,null,2);
Insert into PSI001PL.PRODUCT (PRODUCT_ID,NAME,DESCRIPTION,CODE,BUYPRICE,SELLPRICE,SHOWDATE,STARTTIME,ENDTIME,CATEGORY_CATEGORY_ID) values (4,'Past�is de Bel�m','Os past�is de nata s�o uma das mais populares especialidades da do�aria portuguesa.','C000000002',5.9,9.1,null,null,null,2);
Insert into PSI001PL.PRODUCT (PRODUCT_ID,NAME,DESCRIPTION,CODE,BUYPRICE,SELLPRICE,SHOWDATE,STARTTIME,ENDTIME,CATEGORY_CATEGORY_ID) values (5,'Festival do Panda','Depois do enorme sucesso das edi��es anteriores, o Festival Panda est� de volta.','E000000001',10,11,to_date('12-DEC-13','DD-MON-RR'),'16:00','18:00',3);
Insert into PSI001PL.PRODUCT (PRODUCT_ID,NAME,DESCRIPTION,CODE,BUYPRICE,SELLPRICE,SHOWDATE,STARTTIME,ENDTIME,CATEGORY_CATEGORY_ID) values (6,'Festival no Gelo','Este Natal os Cl�ssicos da Disney v�o estra no Campo Pequeno, entre 25 de Dezembro e 6 de Janeiro.','E000000002',15,16,to_date('28-DEC-13','DD-MON-RR'),'15:00','18:00',3);
Insert into PSI001PL.PRODUCT (PRODUCT_ID,NAME,DESCRIPTION,CODE,BUYPRICE,SELLPRICE,SHOWDATE,STARTTIME,ENDTIME,CATEGORY_CATEGORY_ID) values (7,'Azulejos variados','Azulejos em terracota, fabricados manualmente e pintados � m�o com motivos tradicionais portugueses.','A000000003',4,7.99,null,null,null,1);
Insert into PSI001PL.PRODUCT (PRODUCT_ID,NAME,DESCRIPTION,CODE,BUYPRICE,SELLPRICE,SHOWDATE,STARTTIME,ENDTIME,CATEGORY_CATEGORY_ID) values (8,'Alcofa de Palha','Alcofa fabricada manualmente com  folha de palma.','A000000004',7,17.99,null,null,null,1);
Insert into PSI001PL.PRODUCT (PRODUCT_ID,NAME,DESCRIPTION,CODE,BUYPRICE,SELLPRICE,SHOWDATE,STARTTIME,ENDTIME,CATEGORY_CATEGORY_ID) values (9,'Len�o Tabaqueiro','O len�o �tipo� TABAQUEIRO tamb�m conhecido por �O Alcoba�a� � um len�o   de algod�o, de forma quadrangular , com fundo vermelho, azul ou amarelo, com barras em cores diversas duplas ou simples, fabricado em Alcoba�a.','A000000005',2,5.99,null,null,null,1);
Insert into PSI001PL.PRODUCT (PRODUCT_ID,NAME,DESCRIPTION,CODE,BUYPRICE,SELLPRICE,SHOWDATE,STARTTIME,ENDTIME,CATEGORY_CATEGORY_ID) values (10,'Pinhoada','A pinhoada � um doce muito comum nas feiras, sendo confecionado � base de pinh�es e mel ou a��car.','C000000003',2,3,null,null,null,2);
Insert into PSI001PL.PRODUCT (PRODUCT_ID,NAME,DESCRIPTION,CODE,BUYPRICE,SELLPRICE,SHOWDATE,STARTTIME,ENDTIME,CATEGORY_CATEGORY_ID) values (11,'Bolinhol','O �Bolinhol�, � a mais famosa especialidade gastron�mica de Vizela. � um doce �nico em Portugal, apresenta uma forma rectangular com uma suave cobertura de a��car. A sua massa � levemente h�mida o que lhe atribui um sabor inigual�vel.','C000000004',8,15.99,null,null,null,2);
Insert into PSI001PL.PRODUCT (PRODUCT_ID,NAME,DESCRIPTION,CODE,BUYPRICE,SELLPRICE,SHOWDATE,STARTTIME,ENDTIME,CATEGORY_CATEGORY_ID) values (12,'Doces Brancos','Doces Brancos de P�scoa de Viana do Castelo','C000000005',1,2,null,null,null,2);
Insert into PSI001PL.PRODUCT (PRODUCT_ID,NAME,DESCRIPTION,CODE,BUYPRICE,SELLPRICE,SHOWDATE,STARTTIME,ENDTIME,CATEGORY_CATEGORY_ID) values (13,'Anselmo Ralph','Concerto no Campo Pequeno - 7 de janeiro 2013. Anselmo Ralph, o cantor angolano com maior sucesso na Europa, fecha o ano de 2013 apresentando o seu novo �lbum �A Dor do Cupido�.','E000000003',10,20,to_date('07-DEC-13','DD-MON-RR'),'21:30','23:00',3);
Insert into PSI001PL.PRODUCT (PRODUCT_ID,NAME,DESCRIPTION,CODE,BUYPRICE,SELLPRICE,SHOWDATE,STARTTIME,ENDTIME,CATEGORY_CATEGORY_ID) values (14,'Backstreet Boys','Passar� por 27 cidades e ir� arrancar em Lisboa no pr�ximo dia 18 de Fevereiro. O oitavo disco de est�dio do grupo, �In a World Like This�, ser� apresentado pela primeira vez em Portugal.','E000000004',12,40,to_date('18-DEC-13','DD-MON-RR'),'21:30','22:30',3);
Insert into PSI001PL.PRODUCT (PRODUCT_ID,NAME,DESCRIPTION,CODE,BUYPRICE,SELLPRICE,SHOWDATE,STARTTIME,ENDTIME,CATEGORY_CATEGORY_ID) values (15,'Cirque du Soleil','Fus�o entre a tradi��o chinesa das artes acrob�ticas, com a abordagem multidisciplinar do Cirque du Soleil, Dralion vai buscar a inspira��o � filosofia oriental e a sua demanda incessante pela harmonia entre os humanos e a natureza.','E000000005',20,65,to_date('18-DEC-13','DD-MON-RR'),'21:30','22:30',3);
REM INSERTING into PSI001PL.SYSTEMUSER
SET DEFINE OFF;
Insert into PSI001PL.SYSTEMUSER (SYSTEMUSER_ID,NAME,USERNAME,PASSWORD,EMAIL,USERTYPE_USERTYPE_ID) values (1,'Joaquim Costa','jcosta','99efd3054ce4aeb093d7864ac6e0e29ccb6fa4a9','jcosta@shopcul.pt',1);
Insert into PSI001PL.SYSTEMUSER (SYSTEMUSER_ID,NAME,USERNAME,PASSWORD,EMAIL,USERTYPE_USERTYPE_ID) values (2,'Alberto Gomes','agomes','99efd3054ce4aeb093d7864ac6e0e29ccb6fa4a9','agomes@shopcul.pt',2);
REM INSERTING into PSI001PL.TRANSACTION
SET DEFINE OFF;
Insert into PSI001PL.TRANSACTION (TRANSACTION_ID,PURCHASEDATE,CUSTOMER_CUSTOMER_ID) values (1,to_date('01-NOV-13','DD-MON-RR'),1);
Insert into PSI001PL.TRANSACTION (TRANSACTION_ID,PURCHASEDATE,CUSTOMER_CUSTOMER_ID) values (2,to_date('05-NOV-13','DD-MON-RR'),1);
Insert into PSI001PL.TRANSACTION (TRANSACTION_ID,PURCHASEDATE,CUSTOMER_CUSTOMER_ID) values (3,to_date('23-NOV-13','DD-MON-RR'),1);
REM INSERTING into PSI001PL.TRANSACTIONLINE
SET DEFINE OFF;
Insert into PSI001PL.TRANSACTIONLINE (TRANSACTIONLINE_ID,QUANTITY,PRICEPERUNIT,TRANSACTION_TRANSACTION_ID,PRODUCT_PRODUCT_ID) values (1,12,120,1,1);
Insert into PSI001PL.TRANSACTIONLINE (TRANSACTIONLINE_ID,QUANTITY,PRICEPERUNIT,TRANSACTION_TRANSACTION_ID,PRODUCT_PRODUCT_ID) values (2,1,5,1,2);
Insert into PSI001PL.TRANSACTIONLINE (TRANSACTIONLINE_ID,QUANTITY,PRICEPERUNIT,TRANSACTION_TRANSACTION_ID,PRODUCT_PRODUCT_ID) values (3,2,1.25,1,4);
Insert into PSI001PL.TRANSACTIONLINE (TRANSACTIONLINE_ID,QUANTITY,PRICEPERUNIT,TRANSACTION_TRANSACTION_ID,PRODUCT_PRODUCT_ID) values (4,5,100,2,1);
Insert into PSI001PL.TRANSACTIONLINE (TRANSACTIONLINE_ID,QUANTITY,PRICEPERUNIT,TRANSACTION_TRANSACTION_ID,PRODUCT_PRODUCT_ID) values (5,3,4.5,2,2)
Insert into PSI001PL.TRANSACTIONLINE (TRANSACTIONLINE_ID,QUANTITY,PRICEPERUNIT,TRANSACTION_TRANSACTION_ID,PRODUCT_PRODUCT_ID) values (5,3,4.5,3,2);
REM INSERTING into PSI001PL.USERTYPE
SET DEFINE OFF;
Insert into PSI001PL.USERTYPE (USERTYPE_ID,NAME) values (1,'Admministrador');
Insert into PSI001PL.USERTYPE (USERTYPE_ID,NAME) values (2,'Diretor');
--------------------------------------------------------
--  DDL for Index IMAGE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PSI001PL"."IMAGE_PK" ON "PSI001PL"."IMAGE" ("IMAGE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PSI" ;
--------------------------------------------------------
--  DDL for Index CUSTOMER_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PSI001PL"."CUSTOMER_PK" ON "PSI001PL"."CUSTOMER" ("CUSTOMER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PSI" ;
--------------------------------------------------------
--  DDL for Index COUNTRY_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PSI001PL"."COUNTRY_PK" ON "PSI001PL"."COUNTRY" ("COUNTRY_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PSI" ;
--------------------------------------------------------
--  DDL for Index ADDRESS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PSI001PL"."ADDRESS_PK" ON "PSI001PL"."ADDRESS" ("ADDRESS_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PSI" ;
--------------------------------------------------------
--  DDL for Index CUSTOMER_ADDRESS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PSI001PL"."CUSTOMER_ADDRESS_PK" ON "PSI001PL"."CUSTOMER_ADDRESS" ("CUSTOMER_CUSTOMER_ID", "ADDRESS_ADDRESS_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PSI" ;
--------------------------------------------------------
--  DDL for Index TRANSACTIONLINE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PSI001PL"."TRANSACTIONLINE_PK" ON "PSI001PL"."TRANSACTIONLINE" ("TRANSACTIONLINE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PSI" ;
--------------------------------------------------------
--  DDL for Index TRANSACTION_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PSI001PL"."TRANSACTION_PK" ON "PSI001PL"."TRANSACTION" ("TRANSACTION_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PSI" ;
--------------------------------------------------------
--  DDL for Index PAYOPTION_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PSI001PL"."PAYOPTION_PK" ON "PSI001PL"."PAYOPTION" ("PAYOPTION_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PSI" ;
--------------------------------------------------------
--  DDL for Index USERTYPE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PSI001PL"."USERTYPE_PK" ON "PSI001PL"."USERTYPE" ("USERTYPE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PSI" ;
--------------------------------------------------------
--  DDL for Index CATEGORY_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PSI001PL"."CATEGORY_PK" ON "PSI001PL"."CATEGORY" ("CATEGORY_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PSI" ;
--------------------------------------------------------
--  DDL for Index PRODUCT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PSI001PL"."PRODUCT_PK" ON "PSI001PL"."PRODUCT" ("PRODUCT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PSI" ;
--------------------------------------------------------
--  DDL for Index SYSTEMUSER_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PSI001PL"."SYSTEMUSER_PK" ON "PSI001PL"."SYSTEMUSER" ("SYSTEMUSER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PSI" ;
--------------------------------------------------------
--  DDL for Index ADDRESSTYPE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PSI001PL"."ADDRESSTYPE_PK" ON "PSI001PL"."ADDRESSTYPE" ("ADDRESSTYPE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PSI" ;
--------------------------------------------------------
--  Constraints for Table TRANSACTIONLINE
--------------------------------------------------------

  ALTER TABLE "PSI001PL"."TRANSACTIONLINE" MODIFY ("TRANSACTIONLINE_ID" NOT NULL ENABLE);
 
  ALTER TABLE "PSI001PL"."TRANSACTIONLINE" MODIFY ("TRANSACTION_TRANSACTION_ID" NOT NULL ENABLE);
 
  ALTER TABLE "PSI001PL"."TRANSACTIONLINE" MODIFY ("PRODUCT_PRODUCT_ID" NOT NULL ENABLE);
 
  ALTER TABLE "PSI001PL"."TRANSACTIONLINE" ADD CONSTRAINT "TRANSACTIONLINE_PK" PRIMARY KEY ("TRANSACTIONLINE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PSI"  ENABLE;
--------------------------------------------------------
--  Constraints for Table IMAGE
--------------------------------------------------------

  ALTER TABLE "PSI001PL"."IMAGE" ADD CONSTRAINT "IMAGE_PK" PRIMARY KEY ("IMAGE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PSI"  ENABLE;
 
  ALTER TABLE "PSI001PL"."IMAGE" MODIFY ("IMAGE_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ADDRESSTYPE
--------------------------------------------------------

  ALTER TABLE "PSI001PL"."ADDRESSTYPE" ADD CONSTRAINT "ADDRESSTYPE_PK" PRIMARY KEY ("ADDRESSTYPE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PSI"  ENABLE;
 
  ALTER TABLE "PSI001PL"."ADDRESSTYPE" MODIFY ("ADDRESSTYPE_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table COUNTRY
--------------------------------------------------------

  ALTER TABLE "PSI001PL"."COUNTRY" ADD CONSTRAINT "COUNTRY_PK" PRIMARY KEY ("COUNTRY_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PSI"  ENABLE;
 
  ALTER TABLE "PSI001PL"."COUNTRY" MODIFY ("COUNTRY_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CUSTOMER
--------------------------------------------------------

  ALTER TABLE "PSI001PL"."CUSTOMER" ADD CONSTRAINT "CUSTOMER_PK" PRIMARY KEY ("CUSTOMER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PSI"  ENABLE;
 
  ALTER TABLE "PSI001PL"."CUSTOMER" MODIFY ("CUSTOMER_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CATEGORY
--------------------------------------------------------

  ALTER TABLE "PSI001PL"."CATEGORY" ADD CONSTRAINT "CATEGORY_PK" PRIMARY KEY ("CATEGORY_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PSI"  ENABLE;
 
  ALTER TABLE "PSI001PL"."CATEGORY" MODIFY ("CATEGORY_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ADDRESS
--------------------------------------------------------

  ALTER TABLE "PSI001PL"."ADDRESS" ADD CONSTRAINT "ADDRESS_PK" PRIMARY KEY ("ADDRESS_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PSI"  ENABLE;
 
  ALTER TABLE "PSI001PL"."ADDRESS" MODIFY ("ADDRESS_ID" NOT NULL ENABLE);
 
  ALTER TABLE "PSI001PL"."ADDRESS" MODIFY ("COUNTRY_COUNTRY_ID" NOT NULL ENABLE);
 
  ALTER TABLE "PSI001PL"."ADDRESS" MODIFY ("ADDRESSTYPE_ADDRESSTYPE_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TRANSACTION
--------------------------------------------------------

  ALTER TABLE "PSI001PL"."TRANSACTION" MODIFY ("TRANSACTION_ID" NOT NULL ENABLE);
 
  ALTER TABLE "PSI001PL"."TRANSACTION" ADD CONSTRAINT "TRANSACTION_PK" PRIMARY KEY ("TRANSACTION_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PSI"  ENABLE;
--------------------------------------------------------
--  Constraints for Table CUSTOMER_ADDRESS
--------------------------------------------------------

  ALTER TABLE "PSI001PL"."CUSTOMER_ADDRESS" ADD CONSTRAINT "CUSTOMER_ADDRESS_PK" PRIMARY KEY ("CUSTOMER_CUSTOMER_ID", "ADDRESS_ADDRESS_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PSI"  ENABLE;
 
  ALTER TABLE "PSI001PL"."CUSTOMER_ADDRESS" MODIFY ("CUSTOMER_CUSTOMER_ID" NOT NULL ENABLE);
 
  ALTER TABLE "PSI001PL"."CUSTOMER_ADDRESS" MODIFY ("ADDRESS_ADDRESS_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table USERTYPE
--------------------------------------------------------

  ALTER TABLE "PSI001PL"."USERTYPE" MODIFY ("USERTYPE_ID" NOT NULL ENABLE);
 
  ALTER TABLE "PSI001PL"."USERTYPE" ADD CONSTRAINT "USERTYPE_PK" PRIMARY KEY ("USERTYPE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PSI"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PRODUCT
--------------------------------------------------------

  ALTER TABLE "PSI001PL"."PRODUCT" ADD CONSTRAINT "PRODUCT_PK" PRIMARY KEY ("PRODUCT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PSI"  ENABLE;
 
  ALTER TABLE "PSI001PL"."PRODUCT" MODIFY ("PRODUCT_ID" NOT NULL ENABLE);
 
  ALTER TABLE "PSI001PL"."PRODUCT" MODIFY ("CATEGORY_CATEGORY_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table SYSTEMUSER
--------------------------------------------------------

  ALTER TABLE "PSI001PL"."SYSTEMUSER" ADD CONSTRAINT "SYSTEMUSER_PK" PRIMARY KEY ("SYSTEMUSER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PSI"  ENABLE;
 
  ALTER TABLE "PSI001PL"."SYSTEMUSER" MODIFY ("SYSTEMUSER_ID" NOT NULL ENABLE);
 
  ALTER TABLE "PSI001PL"."SYSTEMUSER" MODIFY ("USERTYPE_USERTYPE_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PAYOPTION
--------------------------------------------------------

  ALTER TABLE "PSI001PL"."PAYOPTION" ADD CONSTRAINT "PAYOPTION_PK" PRIMARY KEY ("PAYOPTION_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PSI"  ENABLE;
 
  ALTER TABLE "PSI001PL"."PAYOPTION" MODIFY ("PAYOPTION_ID" NOT NULL ENABLE);
 
  ALTER TABLE "PSI001PL"."PAYOPTION" MODIFY ("CUSTOMER_CUSTOMER_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table ADDRESS
--------------------------------------------------------

  ALTER TABLE "PSI001PL"."ADDRESS" ADD CONSTRAINT "ADDRESS_ADDRESSTYPE_FK" FOREIGN KEY ("ADDRESSTYPE_ADDRESSTYPE_ID")
	  REFERENCES "PSI001PL"."ADDRESSTYPE" ("ADDRESSTYPE_ID") ON DELETE CASCADE ENABLE;
 
  ALTER TABLE "PSI001PL"."ADDRESS" ADD CONSTRAINT "ADDRESS_COUNTRY_FK" FOREIGN KEY ("COUNTRY_COUNTRY_ID")
	  REFERENCES "PSI001PL"."COUNTRY" ("COUNTRY_ID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CUSTOMER_ADDRESS
--------------------------------------------------------

  ALTER TABLE "PSI001PL"."CUSTOMER_ADDRESS" ADD CONSTRAINT "CUSTOMER_ADDRESS_ADDRESS_FK" FOREIGN KEY ("ADDRESS_ADDRESS_ID")
	  REFERENCES "PSI001PL"."ADDRESS" ("ADDRESS_ID") ON DELETE CASCADE ENABLE;
 
  ALTER TABLE "PSI001PL"."CUSTOMER_ADDRESS" ADD CONSTRAINT "CUSTOMER_ADDRESS_CUSTOMER_FK" FOREIGN KEY ("CUSTOMER_CUSTOMER_ID")
	  REFERENCES "PSI001PL"."CUSTOMER" ("CUSTOMER_ID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table IMAGE
--------------------------------------------------------

  ALTER TABLE "PSI001PL"."IMAGE" ADD CONSTRAINT "IMAGE_PRODUCT_FK" FOREIGN KEY ("PRODUCT_PRODUCT_ID")
	  REFERENCES "PSI001PL"."PRODUCT" ("PRODUCT_ID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PAYOPTION
--------------------------------------------------------

  ALTER TABLE "PSI001PL"."PAYOPTION" ADD CONSTRAINT "PAYOPTION_CUSTOMER_FK" FOREIGN KEY ("CUSTOMER_CUSTOMER_ID")
	  REFERENCES "PSI001PL"."CUSTOMER" ("CUSTOMER_ID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PRODUCT
--------------------------------------------------------

  ALTER TABLE "PSI001PL"."PRODUCT" ADD CONSTRAINT "PRODUCT_CATEGORY_FK" FOREIGN KEY ("CATEGORY_CATEGORY_ID")
	  REFERENCES "PSI001PL"."CATEGORY" ("CATEGORY_ID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table SYSTEMUSER
--------------------------------------------------------

  ALTER TABLE "PSI001PL"."SYSTEMUSER" ADD CONSTRAINT "SYSTEMUSER_USERTYPE_FK" FOREIGN KEY ("USERTYPE_USERTYPE_ID")
	  REFERENCES "PSI001PL"."USERTYPE" ("USERTYPE_ID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TRANSACTION
--------------------------------------------------------

  ALTER TABLE "PSI001PL"."TRANSACTION" ADD CONSTRAINT "TRANSACTION_CUSTOMER_FK" FOREIGN KEY ("CUSTOMER_CUSTOMER_ID")
	  REFERENCES "PSI001PL"."CUSTOMER" ("CUSTOMER_ID") ON DELETE SET NULL ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TRANSACTIONLINE
--------------------------------------------------------

  ALTER TABLE "PSI001PL"."TRANSACTIONLINE" ADD CONSTRAINT "TRANSACTIONLINES_PRODUCT_FK" FOREIGN KEY ("PRODUCT_PRODUCT_ID")
	  REFERENCES "PSI001PL"."PRODUCT" ("PRODUCT_ID") ON DELETE CASCADE ENABLE;
 
  ALTER TABLE "PSI001PL"."TRANSACTIONLINE" ADD CONSTRAINT "TRANSLINES_TRANSACTION_FK" FOREIGN KEY ("TRANSACTION_TRANSACTION_ID")
	  REFERENCES "PSI001PL"."TRANSACTION" ("TRANSACTION_ID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  DDL for Trigger ADDRESSTYPE_ADDRESSTYPE_ID_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "PSI001PL"."ADDRESSTYPE_ADDRESSTYPE_ID_TRG" BEFORE
  INSERT ON addresstype FOR EACH ROW  WHEN (NEW.addresstype_id IS NULL) BEGIN
  SELECT addresstype_addresstype_id_SEQ.NEXTVAL
  INTO :NEW.addresstype_id
  FROM DUAL;
END;
/
ALTER TRIGGER "PSI001PL"."ADDRESSTYPE_ADDRESSTYPE_ID_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger ADDRESS_ADDRESS_ID_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "PSI001PL"."ADDRESS_ADDRESS_ID_TRG" BEFORE
  INSERT ON address FOR EACH ROW  WHEN (NEW.address_id IS NULL) BEGIN
  SELECT address_address_id_SEQ.NEXTVAL INTO :NEW.address_id FROM DUAL;
END;
/
ALTER TRIGGER "PSI001PL"."ADDRESS_ADDRESS_ID_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger CATEGORY_CATEGORY_ID_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "PSI001PL"."CATEGORY_CATEGORY_ID_TRG" BEFORE
  INSERT ON category FOR EACH ROW  WHEN (NEW.category_id IS NULL) BEGIN
  SELECT category_category_id_SEQ.NEXTVAL INTO :NEW.category_id FROM DUAL;
END;
/
ALTER TRIGGER "PSI001PL"."CATEGORY_CATEGORY_ID_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger COUNTRY_COUNTRY_ID_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "PSI001PL"."COUNTRY_COUNTRY_ID_TRG" BEFORE
  INSERT ON country FOR EACH ROW  WHEN (NEW.country_id IS NULL) BEGIN
  SELECT country_country_id_SEQ.NEXTVAL INTO :NEW.country_id FROM DUAL;
END;
/
ALTER TRIGGER "PSI001PL"."COUNTRY_COUNTRY_ID_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger CUSTOMER_CUSTOMER_ID_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "PSI001PL"."CUSTOMER_CUSTOMER_ID_TRG" BEFORE
  INSERT ON customer FOR EACH ROW  WHEN (NEW.customer_id IS NULL) BEGIN
  SELECT customer_customer_id_SEQ.NEXTVAL INTO :NEW.customer_id FROM DUAL;
END;
/
ALTER TRIGGER "PSI001PL"."CUSTOMER_CUSTOMER_ID_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger IMAGE_IMAGE_ID_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "PSI001PL"."IMAGE_IMAGE_ID_TRG" BEFORE
  INSERT ON image FOR EACH ROW  WHEN (NEW.image_id IS NULL) BEGIN
  SELECT image_image_id_SEQ.NEXTVAL INTO :NEW.image_id FROM DUAL;
END;
/
ALTER TRIGGER "PSI001PL"."IMAGE_IMAGE_ID_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger PAYOPTION_PAYOPTION_ID_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "PSI001PL"."PAYOPTION_PAYOPTION_ID_TRG" BEFORE
  INSERT ON payoption FOR EACH ROW  WHEN (NEW.payoption_id IS NULL) BEGIN
  SELECT payoption_payoption_id_SEQ.NEXTVAL INTO :NEW.payoption_id FROM DUAL;
END;
/
ALTER TRIGGER "PSI001PL"."PAYOPTION_PAYOPTION_ID_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger PRODUCT_PRODUCT_ID_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "PSI001PL"."PRODUCT_PRODUCT_ID_TRG" BEFORE
  INSERT ON product FOR EACH ROW  WHEN (NEW.product_id IS NULL) BEGIN
  SELECT product_product_id_SEQ.NEXTVAL INTO :NEW.product_id FROM DUAL;
END;
/
ALTER TRIGGER "PSI001PL"."PRODUCT_PRODUCT_ID_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger SYSTEMUSER_SYSTEMUSER_ID_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "PSI001PL"."SYSTEMUSER_SYSTEMUSER_ID_TRG" BEFORE
  INSERT ON systemuser FOR EACH ROW  WHEN (NEW.systemuser_id IS NULL) BEGIN
  SELECT systemuser_systemuser_id_SEQ.NEXTVAL INTO :NEW.systemuser_id FROM DUAL;
END;
/
ALTER TRIGGER "PSI001PL"."SYSTEMUSER_SYSTEMUSER_ID_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRANSACTIONLINE_TRANSACTIONLIN
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "PSI001PL"."TRANSACTIONLINE_TRANSACTIONLIN" BEFORE
  INSERT ON transactionline FOR EACH ROW  WHEN (NEW.transactionline_id IS NULL) BEGIN
  SELECT transactionline_transactionlin.NEXTVAL
  INTO :NEW.transactionline_id
  FROM DUAL;
END;
/
ALTER TRIGGER "PSI001PL"."TRANSACTIONLINE_TRANSACTIONLIN" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRANSACTION_TRANSACTION_ID_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "PSI001PL"."TRANSACTION_TRANSACTION_ID_TRG" BEFORE
  INSERT ON transaction FOR EACH ROW  WHEN (NEW.transaction_id IS NULL) BEGIN
  SELECT transaction_transaction_id_SEQ.NEXTVAL
  INTO :NEW.transaction_id
  FROM DUAL;
END;
/
ALTER TRIGGER "PSI001PL"."TRANSACTION_TRANSACTION_ID_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger USERTYPE_USERTYPE_ID_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "PSI001PL"."USERTYPE_USERTYPE_ID_TRG" BEFORE
  INSERT ON usertype FOR EACH ROW  WHEN (NEW.usertype_id IS NULL) BEGIN
  SELECT usertype_usertype_id_SEQ.NEXTVAL INTO :NEW.usertype_id FROM DUAL;
END;
/
ALTER TRIGGER "PSI001PL"."USERTYPE_USERTYPE_ID_TRG" ENABLE;
